local wk = require("which-key")
wk.add({
    { "<leader>/", "<Plug>(comment_toggle_linewise_current)", desc = "Comment toggle current line" },
    { "<leader>;", "<cmd>Alpha<CR>", desc = "Dashboard" },
    { "<leader><space>", "<Plug>(comment_toggle_linewise_current)", desc = "comment_toggle_linewise_current" },
    { "<leader>T", group = "Treesitter" },
    { "<leader>Ti", ":TSConfigInfo<cr>", desc = "Info" },
    { "<leader>b", group = "Buffers" },
    { "<leader>bD", "<cmd>BufferLineSortByDirectory<cr>", desc = "Sort by directory" },
    { "<leader>bL", "<cmd>BufferLineSortByExtension<cr>", desc = "Sort by language" },
    { "<leader>bW", "<cmd>noautocmd w<cr>", desc = "Save without formatting (noautocmd)" },
    { "<leader>bb", "<cmd>BufferLineCyclePrev<cr>", desc = "Previous" },
    { "<leader>be", "<cmd>BufferLinePickClose<cr>", desc = "Pick which buffer to close" },
    { "<leader>bf", "<cmd>Telescope buffers previewer=false<cr>", desc = "Find" },
    { "<leader>bh", "<cmd>BufferLineCloseLeft<cr>", desc = "Close all to the left" },
    { "<leader>bj", "<cmd>BufferLinePick<cr>", desc = "Jump" },
    { "<leader>bl", "<cmd>BufferLineCloseRight<cr>", desc = "Close all to the right" },
    { "<leader>bn", "<cmd>BufferLineCycleNext<cr>", desc = "Next" },
    { "<leader>bo", "<cmd>BufferLineCloseOthers<cr>", desc = "BufferCloseOthers" },
    { "<leader>bp", "<cmd>BufferLineTogglePin<cr>", desc = "BufferTogglePin" },
    { "<leader>c", "<cmd>BufferKill<CR>", desc = "Close Buffer" },
    { "<leader>d", group = "Debug" },
    { "<leader>dC", "<cmd>lua require'dap'.run_to_cursor()<cr>", desc = "Run To Cursor" },
    { "<leader>dU", "<cmd>lua require'dapui'.toggle({reset = true})<cr>", desc = "Toggle UI" },
    { "<leader>db", "<cmd>lua require'dap'.step_back()<cr>", desc = "Step Back" },
    { "<leader>dc", "<cmd>lua require'dap'.continue()<cr>", desc = "Continue" },
    { "<leader>dd", "<cmd>lua require'dap'.disconnect()<cr>", desc = "Disconnect" },
    { "<leader>dg", "<cmd>lua require'dap'.session()<cr>", desc = "Get Session" },
    { "<leader>di", "<cmd>lua require'dap'.step_into()<cr>", desc = "Step Into" },
    { "<leader>do", "<cmd>lua require'dap'.step_over()<cr>", desc = "Step Over" },
    { "<leader>dp", "<cmd>lua require'dap'.pause()<cr>", desc = "Pause" },
    { "<leader>dq", "<cmd>lua require'dap'.close()<cr>", desc = "Quit" },
    { "<leader>dr", "<cmd>lua require'dap'.repl.toggle()<cr>", desc = "Toggle Repl" },
    { "<leader>ds", "<cmd>lua require'dap'.continue()<cr>", desc = "Start" },
    { "<leader>dt", "<cmd>lua require'dap'.toggle_breakpoint()<cr>", desc = "Toggle Breakpoint" },
    { "<leader>du", "<cmd>lua require'dap'.step_out()<cr>", desc = "Step Out" },
    { "<leader>e", "<cmd>NvimTreeToggle<cr>", desc = "NvimTree" },
    { "<leader>g", group = "Git" },
    { "<leader>gB", "<cmd>Gitsigns toggle_current_line_blame<cr>", desc = "Toggle Current Line Blame" },
    { "<leader>gC", desc = "<cmd>Telescope git_bcommits<cr>" },
    { "<leader>gR", "<cmd>lua require 'gitsigns'.reset_buffer()<cr>", desc = "Reset Buffer" },
    { "<leader>gb", "<cmd>Telescope git_branches<cr>", desc = "Checkout branch" },
    { "<leader>gc", "<cmd>Telescope git_commits<cr>", desc = "Checkout commit" },
    { "<leader>gd", "<cmd>Gitsigns diffthis HEAD<cr>", desc = "Git Diff" },
    { "<leader>gg", "<cmd>lua require 'plugins.plugin_toggleterm'.lazygit_toggle()<cr>", desc = "Lazygit" },
    { "<leader>gj", "<cmd>lua require 'gitsigns'.next_hunk({navigation_message = false})<cr>", desc = "Next Hunk" },
    { "<leader>gk", "<cmd>lua require 'gitsigns'.prev_hunk({navigation_message = false})<cr>", desc = "Prev Hunk" },
    { "<leader>gl", "<cmd>lua require 'gitsigns'.blame_line()<cr>", desc = "Blame" },
    { "<leader>go", "<cmd>Telescope git_status<cr>", desc = "Open changed file" },
    { "<leader>gp", "<cmd>lua require 'gitsigns'.preview_hunk()<cr>", desc = "Preview Hunk" },
    { "<leader>gr", "<cmd>lua require 'gitsigns'.reset_hunk()<cr>", desc = "Reset Hunk" },
    { "<leader>gs", "<cmd>lua require 'gitsigns'.stage_hunk()<cr>", desc = "Stage Hunk" },
    { "<leader>gu", "<cmd>lua require 'gitsigns'.undo_stage_hunk()<cr>", desc = "Undo Stage Hunk" },
    { "<leader>h", group = "Hop" },
    { "<leader>hw", "<cmd>HopWord<cr>", desc = "HopWord" },
    { "<leader>l", group = "LSP" },
    { "<leader>lI", "<cmd>Mason<cr>", desc = "Mason Info" },
    { "<leader>lS", "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = "Workspace Symbols" },
    { "<leader>la", "<cmd>lua vim.lsp.buf.code_action()<cr>", desc = "Code Action" },
    { "<leader>lc", "<cmd>ChangeEnv<cr>", desc = "Change environment" },
    { "<leader>ld", "<cmd>Telescope diagnostics bufnr=0 theme=get_ivy<cr>", desc = "Buffer Diagnostics" },
    { "<leader>le", "<cmd>Telescope quickfix<cr>", desc = "Telescope Quickfix" },
    { "<leader>lf", "<cmd>lua require('lsp').format()<cr>", desc = "Format" },
    { "<leader>li", "<cmd>LspInfo<cr>", desc = "Info" },
    { "<leader>lj", "<cmd>lua vim.diagnostic.goto_next()<cr>", desc = "Next Diagnostic" },
    { "<leader>lk", "<cmd>lua vim.diagnostic.goto_prev()<cr>", desc = "Prev Diagnostic" },
    { "<leader>ll", "<cmd>lua vim.lsp.codelens.run()<cr>", desc = "CodeLens Action" },
    { "<leader>lq", "<cmd>lua vim.diagnostic.setloclist()<cr>", desc = "Quickfix" },
    { "<leader>lr", "<cmd>lua vim.lsp.buf.rename()<cr>", desc = "Rename" },
    { "<leader>ls", "<cmd>Telesope lsp_document_symbols<cr>", desc = "Document Symbols" },
    { "<leader>lw", "<cmd>Telescope diagnostics<cr>", desc = "Diagnostics" },
    { "<leader>m", group = "Markdown" },
    { "<leader>mf", "<cmd>MarkdownPreview<cr>", desc = "MarkdownPreview" },
    { "<leader>mp", "<cmd>MarkdownPreviewStop<cr>", desc = "MarkdownPreviewStop" },
    { "<leader>mt", "<cmd>MarkdownPreviewToggle<cr>", desc = "MarkdownPreviewToggle" },
    { "<leader>n", group = "neovim" },
    { "<leader>nc", "<cmd>checkhealth<cr>", desc = "checkhealth" },
    { "<leader>nv", "<cmd>lua vim.print(vim.inspect(_G.all3nvim))<cr>", desc = "ShowVars" },
    { "<leader>o", desc = "Open" },
    { "<leader>oB", "<cmd>lua require('browse').browse()<cr>", desc = "browse" },
    { "<leader>ob", "<cmd>OverseerRunBuild<cr>", desc = "OverseerBuild" },
    { "<leader>oc", "<cmd>OverseerRunCmd<cr>", desc = "OverseerRunCmd" },
    { "<leader>oi", "<cmd>OverseerInfo<cr>", desc = "OverseerInfo" },
    { "<leader>or", "<cmd>OverseerRun<cr>", desc = "OverseerRun" },
    { "<leader>ot", "<cmd>OverseerToggle<cr>", desc = "OverseerToggle" },
    { "<leader>ox", "<cmd>OverseerClose<cr>", desc = "OverseerClose" },
    { "<leader>p", group = "Plugins" },
    { "<leader>pS", "<cmd>Lazy clear<cr>", desc = "Status" },
    { "<leader>pc", "<cmd>Lazy clean<cr>", desc = "Clean" },
    { "<leader>pd", "<cmd>Lazy debug<cr>", desc = "Debug" },
    { "<leader>pi", "<cmd>Lazy install<cr>", desc = "Install" },
    { "<leader>pl", "<cmd>Lazy log<cr>", desc = "Log" },
    { "<leader>pp", "<cmd>Lazy profile<cr>", desc = "Profile" },
    { "<leader>ps", "<cmd>Lazy sync<cr>", desc = "Sync" },
    { "<leader>pu", "<cmd>Lazy update<cr>", desc = "Update" },
    { "<leader>q", "<cmd>confirm q<CR>", desc = "Quit" },
    { "<leader>r", group = "Run" },
    { "<leader>rP", "<cmd>AsyncTaskProfile<cr>", desc = "AsyncTaskProfile" },
    { "<leader>rT", "<cmd>lua require('test').input()<cr>", desc = "Test" },
    { "<leader>ra", "<cmd>RunFileArgs<cr>", desc = "run file args" },
    { "<leader>rb", "<cmd>RunBuild<cr>", desc = "run file build" },
    { "<leader>rl", "<cmd>AsyncTaskList<cr>", desc = "AsyncTaskList" },
    { "<leader>rm", "<cmd>AsyncTaskMacro<cr>", desc = "AsyncTaskMacro" },
    { "<leader>rr", "<cmd>RunFile<cr>", desc = "run file" },
    { "<leader>rt", "<cmd>lua require('plugins.plugin_toggleterm').get_term('build_term'):toggle()<cr>", desc = "toggle build" },
    { "<leader>sC", "<cmd>Telescope commands<cr>", desc = "Commands" },
    { "<leader>sH", "<cmd>Telescope highlights<cr>", desc = "Find highlight groups" },
    { "<leader>sM", "<cmd>Telescope man_pages<cr>", desc = "Man Pages" },
    { "<leader>sR", "<cmd>Telescope registers<cr>", desc = "Registers" },
    { "<leader>sb", "<cmd>Telescope git_branches<cr>", desc = "Checkout branch" },
    { "<leader>sc", "<cmd>Telescope colorscheme<cr>", desc = "Colorscheme" },
    { "<leader>sf", "<cmd>Telescope find_files<cr>", desc = "Find File" },
    { "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Find Help" },
    { "<leader>sk", "<cmd>Telescope keymaps<cr>", desc = "Keymaps" },
    { "<leader>sl", "<cmd>Telescope resume<cr>", desc = "Resume last search" },
    { "<leader>sn", "<cmd>Telescope notify<cr>", desc = "Notify" },
    { "<leader>sp", "<cmd>lua require('telescope.builtin').colorscheme({enable_preview = true})<cr>", desc = "Colorscheme with Preview" },
    { "<leader>sr", "<cmd>Telescope oldfiles<cr>", desc = "Open Recent File" },
    { "<leader>ss", "<cmd>Telescope<cr>", desc = "Telescope" },
    { "<leader>st", "<cmd>Telescope live_grep<cr>", desc = "Text" },
    { "<leader>t", group = "toggle" },
    { "<leader>th", "<cmd>ClangdSwitchSourceHeader<cr>", desc = "ClangdSwitchSourceHeader" },
    { "<leader>to", "<cmd>SymbolsOutline<cr>", desc = "SymbolsOutline" },
    { "<leader>tr", "<cmd>TroubleToggle<cr>", desc = "TroubleToggle" },
    { "<leader>tt", "<cmd>Telescope asynctasks all<cr>", desc = "AsyncTasksList" },
    { "<leader>w", "<cmd>w!<CR>", desc = "Save" },
  });
wk.add({
    { "<leader><space>", "<Plug>(comment_toggle_linewise_visual)", desc = "comment_toggle_linewise_visual", mode = "v" },
    { "<leader>sr", "<cmd>lua require 'ssr'.open()<cr>", desc = "RenameBlock", mode = "v" },
})


